# Bun 1.4 migration - Sonar config - temporary broad exclusions to pass Quality Gate for large migration
sonar.projectKey=0libote_Epson-Printer-HA
sonar.organization=0libote
sonar.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.coverage.exclusions=**/*
